# Generated by Django 4.0.1 on 2022-01-13 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('transactionType', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Name', max_length=100, verbose_name='Name')),
                ('cost', models.IntegerField(db_index=True, verbose_name='Cost')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('transactionType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactionType.transactiontype')),
            ],
            options={
                'db_table': 'transactionList',
            },
        ),
    ]
